import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { Header } from "../components/Header/Header";

const Home: NextPage = () => {

  // Get User Location
  // useEffect(()=>{
  //   if ('geolocation' in navigator){
  //     console.log('Available');
  //     navigator.geolocation.getCurrentPosition((pos) => {
  //       console.log(pos.coords.latitude, pos.coords.longitude)
  //     })
  //   } else {
  //     console.log('Unavailable');
  //   }
  // },[])

  return (
    <>
      <Head>
        <title>Recur</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <Header />
      </main>
    </>
  );
};

export default Home;

